JamesBond/Models/ErrorViewModel.cs
using System;

namespace JamesBond.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JamesBond/Models/GadgetModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JamesBond.Models
{
    public class GadgetModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [DisplayName("Appears In")]
        [Required]
        public string AppearsIn { get; set; }
        [DisplayName("With This Actor")]
        [Required]
        public string  WithThisActor { get; set; }

        public GadgetModel()
        {
            Id = 1;
            Name = "";
            Description = "";
            AppearsIn = "";
            WithThisActor = "";
        }

        public GadgetModel(int id, string name, string description, string appearsIn, string withThisActor)
        {
            Id = id;
            Name = name;
            Description = description;
            AppearsIn = appearsIn;
            WithThisActor = withThisActor;
        }
    }
}

JamesBond/Controllers/GadgetsController.cs
using JamesBond.Data;
using JamesBond.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JamesBond.Controllers
{
    public class GadgetsController : Controller
    {
        public IActionResult Index()
        {
            List<GadgetModel> gadgets = new List<GadgetModel>();
            //
            GadgetDAO gadgetDAO = new GadgetDAO();
            gadgets = gadgetDAO.fetchAll();
            return View("Index",gadgets);
        }
        public IActionResult Details(int id)
        {
            GadgetModel gadget = new GadgetModel();
            GadgetDAO gadgetDAO = new GadgetDAO();
            gadget = gadgetDAO.fetchById(id);
            return View("Details", gadget);

        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(GadgetModel newModel)
        {
            GadgetDAO gadgetDAO = new GadgetDAO();
            gadgetDAO.Create(newModel);
            return View("Details", newModel);
        }

        public IActionResult Edit(int id)
        {
            GadgetModel gadget = new GadgetModel();
            GadgetDAO gadgetDAO = new GadgetDAO();
            gadget = gadgetDAO.fetchById(id);
            return View("Edit", gadget);
        }
        [HttpPost]
        public IActionResult Update(GadgetModel updateModel)
        {
            //GadgetModel gadget = new GadgetModel();
            GadgetDAO gadgetDAO = new GadgetDAO();
            gadgetDAO.Update(updateModel);
            return View("Details", updateModel);
        }
        public IActionResult Delete(int id)
        {
            GadgetDAO gadgetDao = new GadgetDAO();
            gadgetDao.Delete(id);
            return Redirect("/gadgets");
        }
        public IActionResult SearchForm()
        {
            return View("SearchForm");
        }
        public IActionResult SearchName(string Name)
        {
            List<GadgetModel> gadgets = new List<GadgetModel>();
            GadgetDAO gadgetDAO = new GadgetDAO();
            gadgets = gadgetDAO.SearchName(Name);
            return View("Index", gadgets);
        }
        public IActionResult SearchDescription(string Description)
        {
            List<GadgetModel> gadgets = new List<GadgetModel>();
            GadgetDAO gadgetDAO = new GadgetDAO();
            gadgets = gadgetDAO.SearchDescription(Description);
            return View("Index", gadgets);
        }
    }
}

JamesBond/Controllers/HomeController.cs
using JamesBond.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace JamesBond.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JamesBond/Views/Gadgets/Create.cshtml
@model JamesBond.Models.GadgetModel

@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>GadgetModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppearsIn" class="control-label"></label>
                <input asp-for="AppearsIn" class="form-control" />
                <span asp-validation-for="AppearsIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WithThisActor" class="control-label"></label>
                <input asp-for="WithThisActor" class="form-control" />
                <span asp-validation-for="WithThisActor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JamesBond/Views/Gadgets/Details.cshtml
@model JamesBond.Models.GadgetModel

<div>
    <h4>GadgetModel</h4>
    <hr />
    <dl class="row">
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppearsIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppearsIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithThisActor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithThisActor)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

JamesBond/Views/Gadgets/Edit.cshtml
@model JamesBond.Models.GadgetModel

@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>GadgetModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="Id" value="@Html.DisplayFor(model => model.Id)"/>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppearsIn" class="control-label"></label>
                <input asp-for="AppearsIn" class="form-control" />
                <span asp-validation-for="AppearsIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WithThisActor" class="control-label"></label>
                <input asp-for="WithThisActor" class="form-control" />
                <span asp-validation-for="WithThisActor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JamesBond/Views/Gadgets/Index.cshtml
@model IEnumerable<JamesBond.Models.GadgetModel>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead class="thead-dark">
        <tr>
           
            <th scope="col"  class="w-50">
                @Html.DisplayNameFor(model => model.Name)
            </th>
           
            <th scope="col" class="w-25">
                @Html.DisplayNameFor(model => model.AppearsIn)
            </th>
           
            <th scope="col" class="w-25"></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td scope="row">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.AppearsIn)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id})
            </td>
        </tr>
}
    </tbody>
</table>

JamesBond/Views/Gadgets/SearchForm.cshtml
@model JamesBond.Models.GadgetModel

@{
    ViewData["Title"] = "SearchForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>SearchForm</h1>

<h4>GadgetModel</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="SearchName" method="get">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" required/>
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>

			<div class="form-group">
				<input type="submit" value="Search" class="btn btn-primary" />
			</div>
		</form>
		<form asp-action="SearchDescription" method="get">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" required/>
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>

			<div class="form-group">
				<input type="submit" value="Search" class="btn btn-primary" />
			</div>
		</form>

	</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JamesBond/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

JamesBond/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JamesBond</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JamesBond</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Gadgets" asp-action="Index">Gadgets</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Gadgets" asp-action="SearchForm">Search</a>
						</li>


					</ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - JamesBond - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>